- type: job
  id: TalosInterdyneCMD
  name: job-name-TalosInterdyneCMD
  description: job-description-TalosInterdyneCMD
  playTimeTracker: JobTalosInterdyneCMD
  startingGear: TalosInterdyneCMDGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance
  - Cargo
  - Salvage
  - Cryogenics
  - External
  - Medical
  - Chemistry
  - Service
  - ChiefMedicalOfficer
  - Command

- type: startingGear
  id: TalosInterdyneCMDGear
  equipment:
    id: TalosInterdyneCMDIDCard
    ears: ClothingHeadsetAltMedical
    jumpsuit: ClothingUniformJumpsuitInterdyneCMO
    belt: ClothingBeltMedicalFilled
    shoes: ClothingShoesBootsInterdyneCmd
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterInterdyne
    head: ClothingHeadInterdyneBeret
    eyes: ClothingEyesInterdyne
  #storage:
    #back:
    #- Stuff
