- type: department
  id: CommandOfficers
  description: department-Command-description
  color: "#291621"
  roles:
   - TalosGorlexVanguard
   - TalosInterdyneCMD
   - TalosCybersunCommandOfficer
   - TalosSELF

- type: department
  id: Gorlex
  description: department-Gorlex-description
  color: "#c13623"
  roles:
   - TalosGorlexVanguard
   - TalosGorlexMasterAtArms
   - TalosGorlex

- type: department
  id: Interdyne
  description: department-Interdyne-description
  color: "#8bbdc7"
  roles:
   - TalosInterdyneCMD
   - TalosInterdyneParamedic
   - TalosInterdyne

- type: department
  id: Cybersun
  description: department-Cybersun-description
  color: "#ebebeb"
  roles:
   - TalosCybersunCommandOfficer
   - TalosCybersunSEA
   - TalosCybersun

# - type: department
#   id: WaffleCo
#   description: department-WaffleCo-description
#   color: "#8d559a"
#   roles:
#    - CargoTechnician
#    - Quartermaster
#    - SalvageSpecialist

- type: department
  id: SELF
  description: department-SELF-description
  color: "#3d598e"
  roles:
   - TalosSELF
   - TalosSELFWorker


- type: department
  id: Gastarbajter
  description: department-Gastarbajter-description
  color: "#3d598e"
  roles:
   - TalosAssistant
